ALTER TABLE "artist_profile" ADD COLUMN "bio" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "genre" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "location" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "contact_email" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "contact_phone" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "website" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "social_links" jsonb;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "streaming_links" jsonb;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "visual_identity" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "colors" jsonb;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "creative_preferences" text;--> statement-breakpoint
ALTER TABLE "artist_profile" ADD COLUMN "other_info" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "legal_name" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "industry" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "products_services" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "location" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "contact_email" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "contact_phone" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "website" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "social_links" jsonb;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "primary_logo" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "secondary_logo" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "colors" jsonb;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "typography" jsonb;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "visual_style" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "imagery_style" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "preferred_layouts" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "references" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "personality" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "voice" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "tone" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "target_audience" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "value_proposition" text;--> statement-breakpoint
ALTER TABLE "brand_profile" ADD COLUMN "other_info" text;